#!/usr/bin/env python
# -*- coding:utf-8 -*-

from peewee import MySQLDatabase, Model
from peewee import PrimaryKeyField, IntegerField, CharField, FloatField, DoubleField, DecimalField
import time
import datetime


def get_str_time(strftime='%Y-%m-%d %H:%M:%S'):
    return datetime.datetime.now().strftime(strftime)


def get_now_time():
    return int(time.time())


db = MySQLDatabase("库",
                   user="root",
                   password="",
                   host="127.0.0.1",
                   port=3306)


class BaseModel(Model):
    class Meta:
        database = db


class XueShuPaper(BaseModel):
    id = PrimaryKeyField()
    technology_crawler_keyword = CharField()
    article_paperid = CharField()
    article_title = CharField()
    article_abstract = CharField()
    article_keyword = CharField()
    article_doi = CharField()
    article_sc_cited = CharField()
    article_year = CharField()
    article_journal_title = CharField()
    article_dl_list = CharField()
    article_sc_search = CharField()

    article_createtime = IntegerField(default=get_now_time())
    article_createdatetime = CharField(default=get_str_time())

    class Meta:
        order_by = ('id',)
        db_table = 'xueshu_paper'


class XueShuAuthors(BaseModel):
    id = PrimaryKeyField()
    xueshu_paper_id = IntegerField()
    author_name = CharField()
    author_organization = CharField()
    author_url = CharField()

    author_createtime = IntegerField(default=get_now_time())
    author_createdatetime = CharField(default=get_str_time())

    class Meta:
        order_by = ('id',)
        db_table = 'xueshu_authors'


class XueshuSimilarReferences(BaseModel):
    id = PrimaryKeyField()
    xueshu_paper_id = IntegerField()
    sc_type = IntegerField()
    sc_pdf_read = CharField()
    sc_research = CharField()
    sc_abstract = CharField()
    sc_keyword = CharField()
    sc_year = CharField()
    sc_title = CharField()
    url = CharField()
    sc_scholarurl = CharField()
    sc_author = CharField()

    sc_createtime = IntegerField(default=get_now_time())
    sc_createdatetime = CharField(default=get_str_time())

    class Meta:
        order_by = ('id',)
        db_table = 'xueshu_similar_references'
